# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyFancyLibrary' do
 
  pod 'React', :path => '../node_modules/react-native/React.podspec'

end
